import { button, icon, sectionTitle, faq, cta, contactForm } from '../components.mjs';

export function home(site) {
  return {
    title: 'Colegio virtual y Homeschool: modalidades y calendarios',
    description: 'Clases en vivo de lunes a jueves o Homeschool con guías, entregas y evaluaciones. Conoce las dos modalidades y calendarios de ALAF.',
    active: 'inicio',
    body: `
<section class="hero" id="inicio"><div class="container hero-layout">
  <div class="hero-copy"><p class="eyebrow hero-label">COLEGIO VIRTUAL + HOMESCHOOL</p><h1>Clases en vivo<br>y homeschool,<br><span>desde casa.</span></h1><p class="hero-description">Conéctate a clases de lunes a jueves o estudia con una organización flexible. En las dos modalidades cuentas con docentes y materiales digitales de ALAF.</p><div class="hero-actions">${button('#servicios','Comparar modalidades')}${button('admisiones/index.html#consulta','Consultar admisiones',{secondary:true})}</div><a class="hero-campus" href="${site.campus}" target="_blank" rel="noopener noreferrer">${icon('book')} ¿Ya estudias en ALAF? Entra al campus ${icon('external')}</a></div>
  <figure class="hero-artistic"><img class="learning-collage" src="assets/mundo-alaf.webp" width="1536" height="1024" alt="Collage artístico de un cuaderno que se convierte en un mundo de casas, caminos y herramientas para aprender" fetchpriority="high"><img class="artistic-alafito" src="assets/alafito-saludo.webp" width="1145" height="1374" alt="Alafito, la mascota de ALAF"><figcaption>Hay más de una forma de aprender.</figcaption><span class="art-label" aria-hidden="true">APRENDER / CREAR / COMPARTIR</span></figure>
</div></section>
<section class="study-facts" id="benefits"><div class="container facts-grid"><div><span class="fact-mark cyan">${icon('calendar')}</span><p><strong>Marzo — diciembre</strong><span>Calendario panameño</span></p></div><div><span class="fact-mark pink">${icon('globe')}</span><p><strong>Agosto — junio</strong><span>Calendario internacional</span></p></div><div><span class="fact-mark lime">${icon('book')}</span><p><strong>Materiales digitales</strong><span>Recursos para estudiar desde casa</span></p></div></div></section>
<section class="section programs-section" id="servicios"><div class="container">${sectionTitle('COMIENZA POR LA MODALIDAD','¿Clases en vivo<br>o trabajo flexible?','La diferencia está en la rutina. Mira cómo se organiza cada opción y qué necesita tu familia para aprovecharla.')}<div class="program-grid">
  <article class="program-card program-virtual"><div class="program-card-top"><span class="program-number">01</span><span class="program-label">VIRTUAL SCHOOL</span>${icon('book')}</div><h3>Un horario de clases.<br>Un grupo para aprender.</h3><p>El estudiante se conecta de lunes a jueves con sus docentes y compañeros. Hay actividades guiadas, participación en clase y trabajo colaborativo.</p><ul class="check-list"><li>${icon('check')} Clases en vivo, de lunes a jueves.</li><li>${icon('check')} Horarios según la etapa del estudiante.</li><li>${icon('check')} Interacción con docentes y compañeros.</li></ul><a class="text-link" href="virtual-school/index.html">Cómo funciona Virtual School ${icon('arrow')}</a></article>
  <article class="program-card program-home"><div class="program-card-top"><span class="program-number">02</span><span class="program-label">HOMESCHOOL ACOMPAÑADO</span>${icon('sun')}</div><h3>Una rutina propia.<br>Con una guía de estudio.</h3><p>La familia organiza el tiempo de estudio con los recursos de ALAF. El programa incluye fechas de entrega y evaluaciones para mantener el avance académico.</p><ul class="check-list"><li>${icon('check')} Estudio flexible dentro de la rutina familiar.</li><li>${icon('check')} Guías, recursos y orientación para padres.</li><li>${icon('check')} Entregas y evaluaciones programadas.</li></ul><a class="text-link" href="homeschool/index.html">Cómo funciona Homeschool ${icon('arrow')}</a></article>
</div><div class="comparison"><div class="comparison-intro"><p class="eyebrow">LAS DIFERENCIAS, DE UN VISTAZO</p><h3>¿Qué cambia<br>en el día a día?</h3><p>El acompañamiento está en ambas. La organización del estudio cambia.</p></div><div class="comparison-table-wrap"><table class="comparison-table"><caption>Comparación de las modalidades de ALAF</caption><thead><tr><th scope="col">En el día a día</th><th scope="col">Virtual School</th><th scope="col">Homeschool</th></tr></thead><tbody><tr><th scope="row">Clases y actividades</th><td>Sesiones en vivo con el grupo.</td><td>Trabajo con guías y materiales.</td></tr><tr><th scope="row">Organización</th><td>Horario de lunes a jueves.</td><td>Rutina familiar y fechas de entrega.</td></tr><tr><th scope="row">Papel de la familia</th><td>Acompañar la conexión y el estudio.</td><td>Organizar y acompañar el trabajo en casa.</td></tr><tr><th scope="row">Evaluación</th><td colspan="2">Diagnósticos, proyectos, rúbricas y reportes de progreso.</td></tr></tbody></table></div></div></div></section>
<section class="section school-section" id="about"><div class="container"><div class="areas-heading">${sectionTitle('QUÉ ENCUENTRAS EN ALAF','Lo que se estudia<br>también se pone en práctica.','Además del trabajo académico, ALAF integra áreas que ayudan al estudiante a resolver problemas y desarrollar proyectos.')}<a class="text-link" href="nosotros/index.html">Conoce la propuesta de ALAF ${icon('arrow')}</a></div><div class="learning-areas"><article class="learning-area-card"><img src="assets/programacion.webp" width="1536" height="1024" loading="lazy" alt="Collage de un computador, un robot de papel y bloques geométricos"><span>01 / PENSAR Y RESOLVER</span><h3>Pensamiento lógico<br>y programación</h3><p>Encontrar patrones, probar soluciones y trabajar con herramientas digitales.</p></article><article class="learning-area-card"><img src="assets/finanzas.webp" width="1536" height="1024" loading="lazy" alt="Collage de una alcancía, sobres de ahorro y una planta"><span>02 / ORGANIZAR RECURSOS</span><h3>Educación<br>financiera</h3><p>Conversar sobre recursos, planificación y decisiones de la vida cotidiana.</p></article><article class="learning-area-card"><img src="assets/emprendimiento.webp" width="1536" height="1024" loading="lazy" alt="Collage de un pequeño puesto de mercado y el cuaderno de su proyecto"><span>03 / DESARROLLAR UNA IDEA</span><h3>Proyectos de<br>emprendimiento</h3><p>Planificar una idea y trabajar en los pasos para convertirla en un proyecto.</p></article></div><p class="subject-note">Inglés desde inicial y un programa progresivo de francés también forman parte de la propuesta de ALAF. Consulta la organización de estas áreas para el grado de interés.</p></div></section>
<section class="section routine-section" id="por-que-nosotros"><div class="container">${sectionTitle('RECURSOS, ACTIVIDADES Y SEGUIMIENTO','Así se organiza<br>el aprendizaje.','Los materiales están en formato digital. El trabajo combina actividades y evaluación para reconocer lo que el estudiante comprende y lo que necesita reforzar.')}<div class="routine-grid"><article><span class="routine-number">1</span><h3>Trabajar con recursos</h3><p>Guías y materiales digitales apoyan las actividades desde casa.</p></article><article><span class="routine-number">2</span><h3>Participar o avanzar</h3><p>Clases en vivo en Virtual School; organización flexible con entregas en Homeschool.</p></article><article><span class="routine-number">3</span><h3>Revisar el progreso</h3><p>Diagnósticos, proyectos, rúbricas y reportes hacen parte de la evaluación.</p></article></div><div class="calendar-note">${icon('calendar')}<p><strong>Elige también el calendario.</strong> ALAF presenta calendario panameño de marzo a diciembre e internacional de agosto a junio. Admisiones confirma las fechas y la disponibilidad del periodo que te interesa.</p></div></div></section>
<section class="section campus-feature"><div class="container campus-layout"><figure class="campus-art"><img src="assets/campus-digital.webp" width="1536" height="1024" loading="lazy" alt="Collage de un computador, libros y carpetas con los colores de ALAF"></figure><div>${sectionTitle('PARA LOS ESTUDIANTES ALAF','Tu acceso<br>al campus virtual.','Si ya estudias en ALAF, entra al campus con tus datos de acceso. Si estás conociendo el colegio, comienza por comparar las modalidades.')}<div class="hero-actions">${button(site.campus,'Entrar al campus',{external:true})}${button('#servicios','Ver modalidades',{secondary:true})}</div></div></div></section>
<section class="section story-section" id="testimonios"><div class="container story-layout"><div><p class="eyebrow">UNA FAMILIA LO CUENTA</p><h2>Su experiencia<br>en Homeschool.</h2><p>Testimonio publicado por ALAF.</p></div><figure class="testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>No puedo sentirme más satisfecha con la educación recibida por mis mellizas. Era exactamente lo que buscábamos.</blockquote><figcaption><span class="testimonial-avatar" aria-hidden="true">MM</span><span><strong>Mónica Mock</strong><span>Mamá de mellizas · Homeschool</span></span></figcaption></figure></div></section>
<section class="section faq-section"><div class="container faq-layout">${sectionTitle('ANTES DE ELEGIR','Respuestas para<br>organizarte mejor.','Consulta la modalidad, el calendario y el grado juntos: esos datos ayudan a definir el programa y sus horarios.')}<div>${faq([
  ['¿Qué días son las clases de Virtual School?','Las clases en vivo se organizan de lunes a jueves. El horario se adapta a la etapa del estudiante; pide a admisiones el horario del grado que necesitas.'],
  ['¿Homeschool tiene fechas de entrega?','Sí. La familia puede organizar el tiempo de estudio, pero hay fechas tope para entregar actividades y presentar evaluaciones.'],
  ['¿Puedo comenzar sin experiencia en homeschool?','ALAF ofrece recursos, tutorías y orientación para padres. Antes de iniciar, conoce cómo se coordina el trabajo y el seguimiento del programa.'],
  ['¿Cómo se evalúa el aprendizaje?','La propuesta incluye diagnósticos, proyectos, rúbricas y reportes. La evaluación permite revisar el progreso del estudiante durante el programa.'],
  ['¿Dónde consulto costos, grados y documentación?','Escribe a admisiones e indica el grado, modalidad y calendario de interés. Solicita los costos, requisitos y la información del certificado emitido antes de matricular.']
])}<a class="text-link faq-more" href="admisiones/index.html#preguntas">Ver información de admisiones ${icon('arrow')}</a></div></div></section>
<section class="section contact-section" id="contacto"><div class="container contact-layout"><div class="contact-copy">${sectionTitle('ADMISIONES ALAF','¿Qué grado<br>te interesa?','Cuéntanos la modalidad y el calendario que buscas. El equipo te comparte horarios, costos y requisitos para ese programa.')}<div class="contact-channel"><span class="channel-icon">${icon('chat')}</span><div><p>Admisiones por WhatsApp</p><a href="https://wa.me/${site.admissions.number}" target="_blank" rel="noopener noreferrer">${site.admissions.label} ${icon('external')}</a></div></div><div class="contact-channel"><span class="channel-icon">${icon('mail')}</span><div><p>Correo electrónico</p><a href="mailto:${site.email}">${site.email}</a></div></div><div class="contact-other"><a href="https://wa.me/${site.attention.number}" target="_blank" rel="noopener noreferrer">Atención general ↗</a><a href="https://wa.me/${site.administration.number}" target="_blank" rel="noopener noreferrer">Administración ↗</a></div></div>${contactForm(site,{compact:true})}</div></section>
${cta(site)}
` };
}
