import { button, icon, sectionTitle, faq, cta, contactForm } from '../components.mjs';

export function about(site) {
  return {title:'Una educación cercana y con propósito',description:'Conoce la propuesta de ALAF International Academy: educación desde casa, acompañamiento humano y habilidades para la vida.',prefix:'../',route:'/nosotros/',active:'nosotros',body:`
<section class="page-hero about-page"><div class="container"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="../index.html">Inicio</a><span aria-hidden="true">/</span><span aria-current="page">Nosotros</span></nav><div class="about-page-intro"><p class="eyebrow">LA PROPUESTA ALAF</p><h1>Virtual School y Homeschool.<br>Un colegio desde casa.</h1><p class="hero-description">Clases en vivo o estudio flexible en familia. Recursos digitales, orientación y evaluación forman parte de las dos modalidades.</p></div><figure class="about-wide-image"><img src="../assets/familia-collage.webp" width="1536" height="1024" alt="Collage artístico de una madre y su hija trabajando en un cuaderno" fetchpriority="high"><figcaption>La educación se construye entre estudiantes, docentes y familias.</figcaption></figure></div></section>
<section class="section"><div class="container statement-layout"><p class="eyebrow">NUESTRA MIRADA</p><div><h2>Docentes, recursos<br>y evaluación.</h2><p>ALAF International Academy ofrece dos formas de estudiar desde casa: Virtual School y Homeschool acompañado. La primera organiza clases en vivo; en la segunda, la familia distribuye el trabajo con las guías del colegio.</p><p>El material está disponible en formato digital. La propuesta evalúa el aprendizaje mediante diagnósticos, proyectos, rúbricas y reportes de progreso.</p></div></div></section>
<section class="section values-section"><div class="container">${sectionTitle('LAS DOS MODALIDADES COMPARTEN','Recursos para estudiar.<br>Seguimiento del trabajo.')}<div class="values-grid"><article><span>01</span><h3>Orientación</h3><p>Los docentes orientan el aprendizaje. En Homeschool, la familia recibe planificación y acompañamiento para organizar el estudio.</p></article><article><span>02</span><h3>Evaluación</h3><p>Diagnósticos, proyectos y rúbricas permiten revisar lo aprendido. Los reportes muestran el progreso del estudiante.</p></article><article><span>03</span><h3>Recursos digitales</h3><p>Las guías y materiales están disponibles en formato digital para trabajar desde casa.</p></article></div></div></section>
<section class="section"><div class="container split-layout"><figure class="editorial-image"><img src="../assets/mundo-alaf.webp" width="1536" height="1024" alt="Ilustración de materiales y piezas de rompecabezas para explorar ideas" loading="lazy"><figcaption>Los recursos son un punto de partida para explorar.</figcaption></figure><div class="editorial-copy">${sectionTitle('CONOCIMIENTOS QUE CONECTAN','Programación, finanzas<br>y emprendimiento.','La propuesta de ALAF integra pensamiento lógico, programación, educación financiera y emprendimiento.')}<p>El pensamiento lógico y la programación se integran con educación financiera y proyectos de emprendimiento. ALAF también presenta inglés desde inicial y un programa progresivo de francés.</p><p>Conoce cómo se trabajan en el programa y el nivel educativo que te interesa.</p>${button('../admisiones/index.html#consulta','Conocer el programa',{secondary:true})}</div></div></section>
<section class="section alafito-section"><div class="container alafito-layout"><div><p class="eyebrow">CONOCE A NUESTRA MASCOTA</p><h2>Alafito también<br>es parte de ALAF.</h2><p>Nuestra mascota conserva su pantalla, su sonrisa y los colores de ALAF. La encontrarás en los materiales de la marca y en esta web.</p><p>Celeste, rosa y verde: los colores del rompecabezas que identifica al colegio.</p><div class="brand-colors" aria-label="Celeste, rosa y verde lima"><span></span><span></span><span></span></div></div><img src="../assets/alafito-leyendo.webp" width="1145" height="1374" alt="Alafito, la mascota de ALAF, leyendo un libro" loading="lazy"></div></section>
${cta(site,'../')}`};
}

export function admissions(site) {
  const steps=[['Indica el grado','Comparte la etapa educativa o el grado que necesita el estudiante.'],['Elige cómo estudiar','Consulta Virtual School o Homeschool y el calendario de interés.'],['Pide los detalles','Solicita horarios, costos y los servicios incluidos en ese programa.'],['Revisa los documentos','Confirma requisitos de matrícula y documentación académica antes de iniciar.']];
  return {title:'Admisiones y orientación para familias',description:'Consulta modalidades, niveles, calendario, costos y requisitos de ALAF. Prepara tu consulta de admisión y habla con nuestro equipo.',prefix:'../',route:'/admisiones/',active:'admisiones',body:`
<section class="page-hero admissions-page"><div class="container"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="../index.html">Inicio</a><span aria-hidden="true">/</span><span aria-current="page">Admisiones</span></nav><div class="admissions-intro"><div><p class="eyebrow">ADMISIONES / ALAF</p><h1>Grado. Modalidad.<br>Calendario.</h1><p class="hero-description">Con esos tres datos, admisiones puede compartir el horario, costos y requisitos del programa que buscas.</p>${button('#consulta','Consultar admisiones')}</div><aside class="admissions-note"><span class="feature-icon">${icon('heart')}</span><h2>Pide los detalles<br>antes de matricular.</h2><p>Antes de matricular, pregunta por el programa, el acompañamiento y la documentación académica que necesitas.</p><a class="text-link" href="https://wa.me/${site.admissions.number}" target="_blank" rel="noopener noreferrer">${site.admissions.label} ${icon('external')}</a></aside></div></div></section>
<section class="section steps-section"><div class="container">${sectionTitle('PREPARA TU CONSULTA','La información<br>que necesitas pedir.')}<ol class="steps-grid">${steps.map(([title,text],index)=>`<li><span class="step-number">0${index+1}</span><h3>${title}</h3><p>${text}</p></li>`).join('')}</ol></div></section>
<section class="section admissions-contact" id="consulta"><div class="container contact-layout"><div class="contact-copy">${sectionTitle('CONSULTA EL PROGRAMA','Escribe a<br>admisiones.','Puedes preparar una consulta o escribir directamente al equipo de admisiones.')}<div class="contact-channel"><span class="channel-icon">${icon('chat')}</span><div><p>WhatsApp de admisión</p><a href="https://wa.me/${site.admissions.number}" target="_blank" rel="noopener noreferrer">${site.admissions.label} ${icon('external')}</a></div></div><div class="contact-channel"><span class="channel-icon">${icon('mail')}</span><div><p>Correo electrónico</p><a href="mailto:${site.email}">${site.email}</a></div></div><div class="before-contact"><h3>Para una conversación útil</h3><ul><li>Grado o etapa educativa de interés.</li><li>Modalidad que desean conocer.</li><li>Calendario y disponibilidad familiar.</li><li>Dudas sobre costos y requisitos.</li></ul></div></div>${contactForm(site)}</div></section>
<section class="section"><div class="container faq-layout">${sectionTitle('INFORMACIÓN PARA DECIDIR','Costos, requisitos<br>y documentación.')}<div>${faq([
['¿Qué niveles y grados están disponibles?','Comparte el grado de interés con admisiones. El equipo puede confirmar la oferta vigente y orientar a tu familia sobre el programa.'],
['¿Dónde puedo consultar los costos?','Admisiones te comparte los costos y los servicios incluidos para la modalidad y el programa de interés. Pregunta también por los conceptos adicionales que puedan aplicar.'],
['¿Qué calendario puedo elegir?','ALAF presenta calendario panameño de marzo a diciembre e internacional de agosto a junio. Confirma la fecha de inicio y disponibilidad del programa para el periodo de interés.'],
['¿Qué documentos necesito para matricular?','Los requisitos pueden depender del programa y la trayectoria educativa del estudiante. Solicita la lista vigente de documentos antes de iniciar el proceso.'],
['¿Qué debo revisar sobre la documentación académica?','Pide información sobre el certificado emitido, la institución responsable y los trámites disponibles. Si planeas continuar estudios en otra institución o país, consulta también los requisitos del destino.'],
['¿Puedo solicitar orientación antes de elegir?','Sí. Cuéntanos sobre la rutina de tu familia y las modalidades que te interesan. El equipo puede explicar sus diferencias para ayudarte a decidir.']
],'preguntas')}</div></div></section>`};
}

export function privacy(site) {
  return {title:'Información de privacidad',description:'Información sobre los datos que se utilizan para atender consultas de admisión en la web de ALAF.',prefix:'../',route:'/privacidad/',active:'privacidad',body:`<section class="section legal-page"><div class="container prose"><p class="eyebrow">INFORMACIÓN PARA LAS FAMILIAS</p><h1>Privacidad y<br><em>consultas de admisión.</em></h1><p>Esta página explica el uso de los datos en el formulario de consulta de esta web.</p><h2>Qué datos puedes compartir</h2><p>El formulario solicita el nombre del adulto responsable, correo electrónico, teléfono opcional, modalidad de interés y un mensaje. Evita incluir documentos de identidad, datos de salud u otra información sensible en la consulta inicial.</p><h2>Para qué se utilizan</h2><p>Los datos se utilizan para atender tu consulta, explicar la propuesta educativa y orientar el siguiente paso de admisión. El formulario requiere tu consentimiento antes de preparar o enviar la consulta.</p><h2>Consulta por WhatsApp</h2><p>Cuando eliges WhatsApp, la web prepara un mensaje. El mensaje se prepara localmente en tu navegador. Al abrir el enlace, los datos incluidos se comparten con WhatsApp. Puedes revisar el mensaje antes de enviarlo. El uso de WhatsApp está sujeto a las condiciones y la privacidad de ese servicio.</p><h2>Consulta por correo</h2><p>Si el envío por correo está habilitado, los datos se transmiten al servicio de envío para entregar la consulta a ALAF. Si el envío falla, la web te lo informa y permite contactar por los canales alternativos.</p><h2>Almacenamiento en el navegador</h2><p>Esta web no guarda los datos del formulario en el almacenamiento del navegador ni incorpora herramientas publicitarias. El proveedor de hosting puede registrar información técnica de acceso para operar el servicio.</p><h2>Cómo contactar</h2><p>Para consultar sobre el tratamiento, conservación, acceso o eliminación de los datos que has compartido, escribe a <a href="mailto:${site.email}">${site.email}</a>. ALAF International Academy es el contacto responsable de atender estas solicitudes.</p><h2>Imágenes</h2><p>Las escenas de aprendizaje y los materiales de esta web son ilustraciones creadas para presentar la propuesta educativa. Alafito es la mascota de ALAF.</p>${button('../admisiones/index.html#consulta','Volver a admisiones',{secondary:true})}</div></section>`};
}

export function notFound(site) {
  return {title:'Página no encontrada',description:'Vuelve al inicio de ALAF International Academy para explorar las modalidades y la información de admisión.',prefix:'/',route:'/404.html',active:'404',noindex:true,body:`<section class="section error-page"><div class="container"><p class="eyebrow">404 · PÁGINA NO ENCONTRADA</p><h1>Volvamos a<br><em>encontrar el camino.</em></h1><p>La página que buscas no está disponible. Puedes volver al inicio o consultar a nuestro equipo.</p><div class="hero-actions">${button('/index.html','Volver al inicio')}${button('/admisiones/index.html','Consultar admisiones',{secondary:true})}</div><img src="/assets/alafito-guia.webp" width="1145" height="1374" alt="Alafito te acompaña a volver al inicio"></div></section>`};
}
