import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { escapeHTML } from '../src/components.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const assets=JSON.parse(await readFile(path.join(root,'src/assets/assets.json'),'utf8'));
const styles=`*{box-sizing:border-box}body{margin:0;font:16px/1.7 'Segoe UI',Arial,sans-serif;color:#183545;background:#fff}main{max-width:1250px;margin:auto;padding:55px 28px}h1{font-size:clamp(32px,5vw,55px);line-height:1.12;letter-spacing:-2px;margin:0 0 20px}p{max-width:750px}a{color:inherit;text-underline-offset:4px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:25px;margin-top:40px}article{border:1px solid #183545;padding:22px;border-radius:8px}article:nth-child(3n+1){border-top:5px solid #a2dbe0}article:nth-child(3n+2){border-top:5px solid #e8bfda}article:nth-child(3n){border-top:5px solid #b0d468}article img{width:100%;height:210px;object-fit:contain;background:#fff}article h2{font-size:19px;margin:20px 0 10px}article p{font-size:12px;color:#4c6370;margin:10px 0}article a{font-size:13px;margin-right:14px}.actions{display:flex;gap:15px;flex-wrap:wrap;margin-top:30px}.button{display:inline-block;text-decoration:none;padding:12px 20px;background:#183545;color:#fff;border:1px solid #183545;border-radius:6px;font-weight:600}.secondary{background:#b0d468;color:#183545}.hero{display:grid;grid-template-columns:1fr 1fr;gap:35px;align-items:center}.hero img{width:100%}.note{font-size:13px;color:#4c6370;border-top:1px solid #d3e0e5;padding-top:25px;margin-top:40px}@media(max-width:700px){main{padding:35px 20px}.hero{grid-template-columns:1fr}}`;
await writeFile(path.join(root,'ASSETS.html'),`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Biblioteca artística ALAF</title><style>${styles}</style></head><body><main><h1>La familia artística<br>de ALAF.</h1><p>11 ilustraciones nuevas en formato WebP, con originales PNG incluidos. Las tres poses de Alafito conservan fondo transparente. El logo oficial se mantiene en su archivo original.</p><div class="actions"><a class="button" href="dist/index.html">Abrir la web</a><a class="button secondary" href="src/assets/logo.png">Ver el logo original</a></div><div class="grid">${assets.map(asset=>`<article><img src="src/assets/${asset.web}" width="${asset.webWidth}" height="${asset.webHeight}" alt="${escapeHTML(asset.title)}"><h2>${escapeHTML(asset.title)}</h2><p>${asset.originalWidth} × ${asset.originalHeight} px · ${asset.transparent?'PNG con transparencia':'Ilustración sobre blanco'}<br>WebP: ${Math.round(asset.webBytes/1024)} KB</p><a href="src/assets/${asset.original}" download>Original PNG</a><a href="src/assets/${asset.web}" download>WebP</a></article>`).join('')}</div><p class="note">Generadas con ImageGen. Los prompts y la procedencia están en docs/ASSETS-Y-PROMPTS.md. Las escenas con personas son ilustraciones ficticias.</p></main></body></html>`,'utf8');
await writeFile(path.join(root,'ABRIR-WEB.html'),`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ALAF — abre la entrega</title><style>${styles}</style></head><body><main><div class="hero"><div><h1>Tu nueva web<br>de ALAF.</h1><p>Diseño artístico, siete páginas, logo original, tres poses de Alafito y una biblioteca de ilustraciones. Todo está incluido en esta carpeta.</p><div class="actions"><a class="button" href="dist/index.html">Abrir la web</a><a class="button secondary" href="ASSETS.html">Explorar los assets</a></div></div><img src="dist/assets/mundo-alaf.webp" width="1536" height="1024" alt="Collage artístico del mundo de aprendizaje ALAF"></div><p class="note"><strong>Para publicarla:</strong> sube el contenido de dist/ al hosting. Para editar, revisa README.md. El contacto por WhatsApp está listo; el envío opcional por correo requiere configurar el servicio. Extrae todo el ZIP antes de abrir la web.</p></main></body></html>`,'utf8');
console.log(`Biblioteca preparada: ${assets.length} assets y guía de apertura.`);
